name:                Chesskell
version:             0.1.0.0
github:              "teremax/Chesskell"
license:             BSD3
author:              "Maxim Tereshchuk"
maintainer:          "m.a.tereshchuk@gmail.com"
copyright:           "2019 Maxim Tereshchuk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/teremax/Chesskell#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- matrix
- lens
- containers
- gloss
- vector

library:
  source-dirs: src

executables:
  Chesskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chesskell

tests:
  Chesskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Chesskell
